---
- name: Only works on Raspberry Pi OS Buster
  assert:
    that:
      - ansible_facts['lsb']['id'] == 'Raspbian'
      - ansible_facts['lsb']['major_release'] == '10'

- name: Disable Bluetooth
  ansible.builtin.systemd:
    name: bluetooth
    enabled: no

- name: Disable hciuart
  ansible.builtin.systemd:
    name: hciuart
    enabled: no

- name: Disable Raspberry Pi audio
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^.*dtparam=audio='
    line: dtparam=audio=off

- name: Disable Raspberry Pi Bluetooth
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^.*dtoverlay=disable-bt'
    line: dtparam=disable-bt

- name: Set memory split
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^.*gpu_mem='
    line: gpu_mem=16
