#!/usr/bin/python3

import sys
import os
from datetime import datetime
from pathlib import Path
import shutil
import traceback
import blinkt

def main():
    if len(sys.argv) < 3:
        print('Usage: camera-import-msd SRC DEST')
        sys.exit(1)
    
    src = sys.argv[1]
    dest = sys.argv[2]

    blinkt.set_clear_on_exit()
    blinkt.set_brightness(0.1)
    c = 0

    for file in Path(src).glob('DCIM/*/*.*'):
        if file.is_file() != True:
            continue

        blinkt.set_pixel(c % blinkt.NUM_PIXELS, 0, 0, 0)
        c = c + 1
        blinkt.set_pixel(c % blinkt.NUM_PIXELS, 31, 31, 31)
        blinkt.show()

        stat = file.stat()
        dest_dir = Path(dest).joinpath(datetime.fromtimestamp(stat.st_mtime).strftime('%Y-%m-%d'))
        if dest_dir.exists() != True:
            dest_dir.mkdir(parents=True)

        dest_file = dest_dir.joinpath(file.name)
        if dest_file.exists() == True:
            if dest_file.stat().st_size == stat.st_size:
                print('Skipping existing file %s' % (file.name))
                continue
            print('Warning: existing file %s has different size, overwriting.' % dest_file)

        try:
            print("'%s' -> '%s'" % (str(file), str(dest_file)))
            shutil.copy2(str(file), str(dest_file))
        except Exception as e:
            pass


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(10)
    except Exception:
        traceback.print_exc()
        sys.exit(1)
